name: lint-action
runs:
  using: "composite"
  steps:
    - name: Install modules
      run: npm install
      shell: bash 
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
      shell: bash 
