name: lint-action
runs:
  using: "composite"
  steps:
    - name: Install modules
      run: yarn
      shell: bash 
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx
      shell: bash 
