name: test-action
inputs:
  branch:
    description: 'Branch to run this action on'
    required: true
on: 
  push:
    branches:
      - ${{env.INPUT_BRANCH}}
  pull_request:
    branches:
      - ${{env.INPUT_BRANCH}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
