name: docs-action
runs:
  using: "composite"
  steps:
    - name: Run automatic doc generation
      uses: andstor/jsdoc-action@v1
      with:
        source_dir: ./pipeline
        recurse: true
        output_dir: ./docs
        config_file: jsdocs.config.json
        template: minami
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs
        publish_branch: gh-pages # OVERWRITES COMMIT HISTORY - DO NOT CHANGE FROM THIS BRANCH      