name: Main Branch Action

on: [push, pull_request]

jobs:

# TODO: Make jobs dependent on each other

    lint:
      name: lint-job
      runs-on: ubuntu-latest
#      needs: format
      steps:
        - uses: actions/checkout@v2
          with:
            ref: pipeline-phase-1.1-fix-linting-npm
        - name: Run linter on new code
          uses: ./.github/workflows/actions/lint-action

    test:
      name: test-job
      runs-on: ubuntu-latest
#      needs: [lint, format]
      steps:
        - uses: actions/checkout@v2
          with:
            ref: pipeline-phase-1.1
        - name: Run full suite of tests on new code
          uses: ./.github/workflows/actions/all-tests-action

