name: Main Branch Action 

on: [push, pull_request]

jobs:

# TODO: Make jobs dependent on each other
# TODO: Change ref to main after testing

    lint:
      name: lint-job
      runs-on: ubuntu-latest
#      needs: format
      steps:
        - uses: actions/checkout@v2
          with:
            ref: pipeline-phase-1.1-jsdocs-action
        - name: Run linter on new code
          uses: ./.github/workflows/actions/lint-action

    test:
      name: test-job
      runs-on: ubuntu-latest
#      needs: [lint, format]
      steps:
        - uses: actions/checkout@v2
          with:
            ref: pipeline-phase-1.1-jsdocs-action
        - name: Run full suite of tests on new code
          uses: ./.github/workflows/actions/all-tests-action

    docs:
      name: docs-job
      runs-on: ubuntu-latest
#      needs: format
      steps:
        - uses: actions/checkout@v2
        - name: Run automatic doc generation
          uses: andstor/jsdoc-action@v1
          with:
            ref: pipeline-phase-1.1-jsdocs-action
            source_dir: ./pipeline
            output_dir: ./docs
            config_file: jsdocs.config.json
            template: minami


