name: Main Branch Action

on: [push, pull_request]

jobs:

# TODO: Make format job. Might, be configurable with eslint + prettier so this
# job could be added into ./actions/lint-action/action.yaml


# TODO: Make jobs dependent

    lint:
      name: lint-job
      runs-on: ubuntu-latest
#      needs: format
      steps:
        - uses: actions/checkout@v2
          with:
            ref: pipeline-phase-1.1
        - name: Run linter on new code
          uses: ./.github/workflows/actions/lint-action

    test:
      name: test-job
      runs-on: ubuntu-latest
#      needs: [lint, format]
      steps:
        - uses: actions/checkout@v2
          with:
            ref: pipeline-phase-1.1
        - name: Run full suite of tests on new code
          uses: ./.github/workflows/actions/all-tests-action
